name: forest-env
channels:
  - anaconda
  - conda-forge
  - pytorch
  - jmcmurray
  - nvidia
dependencies:
  - python=3.9
  - numpy
  - pytorch
  - pytorch-cuda=11.7
  #- torchvision
  - pytorch-lightning
  - scikit-learn
  #- tensorboard
  - os
  #- matplotlib
  - pandas
  #- scikit-learn
  #- jupyter
  #- xgboost
  #- lightgbm
  #- seaborn
  #- pytorch_tabnet